services:

  tatd_bot:
    build: https://github.com/toro89rus/vk_comments_monitor.git
    command: ["make", "run"]
    env_file:
      - .env
    environment:
      - REDIS=REDIS
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
